# Generated by Django 5.2.3 on 2025-07-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_booking_guest_email_booking_guest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
