# Generated by Django 5.2.3 on 2025-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_booking_is_guest_order_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
