# Generated by Django 5.2.3 on 2025-07-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_cartitem_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='guest_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='guest_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
