# Generated by Django 5.2.3 on 2025-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_alter_booking_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
